/*
 * Utility functions for trap handling in Supervisor mode.
 */

#include "riscv.h"
#include "process.h"
#include "strap.h"
#include "syscall.h"
#include "string.h"
#include "spike_interface/spike_file.h"
#include "spike_interface/spike_utils.h"

static void print_code_line(char *path, int lineno) {
  spike_file_t *f = spike_file_open(path, O_RDONLY, 0);
  if (IS_ERR_VALUE((uint64)f)) return;

  char buf[256];
  int current_line = 1;
  int col = 0;
  char c;

  while (1) {
    long n = spike_file_read(f, &c, 1);
    if (n <= 0) break;

    if (c == '\n') {
      if (current_line == lineno) {
        buf[col] = 0;
        sprint("  %s\n", buf);
        break;
      }
      current_line++;
      col = 0;
    } else if (current_line == lineno) {
      if (col < sizeof(buf) - 1) {
        buf[col++] = c;
      }
    }
  }

  spike_file_close(f);
}

static void print_debug_info(uint64 epc) {
  if (!current || !current->line) return;

  int best_i = -1;
  for (int i = 0; i < current->line_ind; i++) {
    if (current->line[i].addr <= epc) {
      if (best_i == -1 || current->line[i].addr > current->line[best_i].addr) {
        best_i = i;
      }
    }
  }

  if (best_i != -1) {
    int file_idx = current->line[best_i].file;
    int line_num = current->line[best_i].line;
    char *filename = current->file[file_idx].file;
    int dir_idx = current->file[file_idx].dir;
    char *dirname = current->dir[dir_idx];

    char path[128];
    strcpy(path, dirname);
    if (path[strlen(path) - 1] != '/') {
      strcat(path, "/");
    }
    strcat(path, filename);

    sprint("Runtime error at %s:%d\n", path, line_num);
    print_code_line(path, line_num);
  }
}

//
// handling the syscalls. will call do_syscall() defined in kernel/syscall.c
//
static void handle_syscall(trapframe *tf) {
  // tf->epc points to the address that our computer will jump to after the trap handling.
  // for a syscall, we should return to the NEXT instruction after its handling.
  // in RV64G, each instruction occupies exactly 32 bits (i.e., 4 Bytes)
  tf->epc += 4;

  // TODO (lab1_1): remove the panic call below, and call do_syscall (defined in
  // kernel/syscall.c) to conduct real operations of the kernel side for a syscall.
  // IMPORTANT: return value should be returned to user app, or else, you will encounter
  // problems in later experiments!
  tf->regs.a0 = do_syscall(tf->regs.a0,tf->regs.a1,tf->regs.a2,tf->regs.s3,tf->regs.a4,tf->regs.a5,tf->regs.a6,tf->regs.a7);

}

//
// global variable that store the recorded "ticks". added @lab1_3
static uint64 g_ticks = 0;
//
// added @lab1_3
//
void handle_mtimer_trap() {
  sprint("Ticks %d\n", g_ticks);
  // TODO (lab1_3): increase g_ticks to record this "tick", and then clear the "SIP"
  // field in sip register.
  // hint: use write_csr to disable the SIP_SSIP bit in sip.
  g_ticks++;
  write_csr(sip,read_csr(sip) & (~SIP_SSIP));

}

//
// kernel/smode_trap.S will pass control to smode_trap_handler, when a trap happens
// in S-mode.
//
void smode_trap_handler(void) {
  // make sure we are in User mode before entering the trap handling.
  // we will consider other previous case in lab1_3 (interrupt).
  if ((read_csr(sstatus) & SSTATUS_SPP) != 0) panic("usertrap: not from user mode");

  assert(current);
  // save user process counter.
  current->trapframe->epc = read_csr(sepc);

  // if the cause of trap is syscall from user application.
  // read_csr() and CAUSE_USER_ECALL are macros defined in kernel/riscv.h
  uint64 cause = read_csr(scause);

  // we need to handle the timer trap @lab1_3.
  if (cause == CAUSE_USER_ECALL) {
    handle_syscall(current->trapframe);
  } else if (cause == CAUSE_MTIMER_S_TRAP) {  //soft trap generated by timer interrupt in M mode
    handle_mtimer_trap();
  } else {
    print_debug_info(read_csr(sepc));
    if (cause == CAUSE_ILLEGAL_INSTRUCTION) {
       sprint("Illegal instruction!\n");
    }

    panic( "System is shutting down with exit code -1." );
  }

  // continue (come back to) the execution of current process.
  switch_to(current);
}
